spring:
  application:
    name: WUD Games Website Backend
  datasource:
    url: jdbc:h2:file:./data/mydb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB


server:
  port: 8080
  servlet:
    context-path: /


springdoc:
  swagger-ui:
    url: /WudGamesWebsite.yaml
